version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - app-network

  # Development service with hot reloading
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./web:/app/web
      - /app/web/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  
  # Add more services as needed, for example:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app-network

  # database:
  #   image: postgres:13
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=appdb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge
  vpn_network:
    external: false

# volumes:
#   postgres_data: 